# Generated by Django 4.1.5 on 2023-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_watchlist_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_path',
            field=models.URLField(max_length=300),
        ),
    ]
