# Generated by Django 4.1.5 on 2023-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_path',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
