# Generated by Django 4.1.5 on 2023-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
