# Generated by Django 4.1.5 on 2023-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
