# Generated by Django 4.1.5 on 2023-02-02 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
