# Generated by Django 4.1.5 on 2023-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('HOME APPLIANCES', 'Home Appliances'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
