# Generated by Django 4.1.5 on 2023-02-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlisting_highest_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='initial_price',
            new_name='price',
        ),
    ]
